sudo apt install git -y
sudo apt fakeroot  -y
sudo apt build-essential  -y
sudo apt ncurses-dev  -y
sudo apt xz-utils  -y
sudo apt libssl-dev  -y
sudo apt bc  -y
sudo apt flex  -y
sudo apt libelf-dev  -y
sudo apt bison  -y
sudo apt mc  -y
sudo apt tree  -y
sudo apt vim  -y
sudo apt curl  -y
sudo apt python3  -y
sudo apt cmake  -y
sudo apt scons  -y
sudo apt neofetch  -y
sudo apt openssh-server  -y
sudo apt minicom -y
sudo apt kmod -y
sudo apt cpio -y
sudo apt mkimage -y
sudo apt gawk -y
sudo apt clang -y
sudo apt rustc -y
sudo apt bindgen -y
sudo apt binutils -y
sudo apt pahole -y
sudo apt jfsutils -y
sudo apt btrfsck -y
sudo apt reiserfsck -y
sudo apt xfs_db -y
sudo apt pccardctl -y
sudo apt quota -y
sudo apt procps -y
sudo apt mcelog -y
sudo apt fsck.jfs -y
