sudo apt install git -y
sudo apt fakeroot  -y
sudo apt build-essential  -y
sudo apt ncurses-dev  -y
sudo apt xz-utils  -y
sudo apt libssl-dev  -y
sudo apt bc  -y
sudo apt flex  -y
sudo apt libelf-dev  -y
sudo apt bison  -y
sudo apt mc  -y
sudo apt tree  -y
sudo apt vim  -y
sudo apt curl  -y
sudo apt python3  -y
sudo apt cmake  -y
sudo apt scons  -y
sudo apt neofetch  -y
sudo apt openssh-server  -y
sudo apt minicom -y
