sudo apt install git -y
sudo apt install fakeroot  -y
sudo apt install build-essential  -y
sudo apt install ncurses-dev  -y
sudo apt install xz-utils  -y
sudo apt install libssl-dev  -y
sudo apt install bc  -y
sudo apt install flex  -y
sudo apt install libelf-dev  -y
sudo apt install bison  -y
sudo apt install mc  -y
sudo apt install tree  -y
sudo apt install vim  -y
sudo apt install curl  -y
sudo apt install python3  -y
sudo apt install cmake  -y
sudo apt install scons  -y
sudo apt install neofetch  -y
sudo apt install openssh-server  -y
sudo apt install minicom -y
sudo apt install kmod -y
sudo apt install cpio -y
sudo apt install mkimage -y
sudo apt install gawk -y
sudo apt install clang -y
sudo apt install rustc -y
sudo apt install bindgen -y
sudo apt install binutils -y
sudo apt install pahole -y
sudo apt install jfsutils -y
sudo apt install btrfsck -y
sudo apt install reiserfsck -y
sudo apt install xfs_db -y
sudo apt install pccardctl -y
sudo apt install quota -y
sudo apt install procps -y
sudo apt install mcelog -y
sudo apt install fsck.jfs -y
sudo apt install linux-headers-$(uname -r) -y
sudo apt install ccache -y
sudo apt install make -y
sudo apt install fuse -y

